### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by jdeast**

### CODE REVIEW

**Comment by T0T4R4** [comment]
Sorry for the spam - I did not noticed that all my comments would end up here on this PR.
Are you bringing develop into master now ? Is there a reason to keep develop if there is no proper release cycle ? Why not adopting the github model (enforcing pull-requests) from then on ?

**Comment by jdeast** [comment]
There's no reason to keep develop except for my lack of familiarity with
git/github. Not sure what "enforcing pull-requests" means, but I'm all for
a more sensible approach. I have several updates that will probably
conflict with yours. They should be easy to resolve, but will take some
time.

Jason

PS: hope you're not a Dodgers fan...

**Comment by T0T4R4** [comment]
Hi Jason,
If you were not familiar with git, then that is understandable. 
Basically I would recommend you to only work off one branch, master, as soon as you've merged develop into master, delete develop. Then there should be some settings on the git repo to enforce pull-requests.
As soon as you start working on something, create a 'feature' branch locally, name it 'feature/myfeaturename' (prefix it).
Once the change has been unit tested, and that branch pushed to github (aka remote), then on github create a pull-request to merge the feature branch to develop. That enforces peer-reviews and is considered to be good practice. 
Once you've done it once, it's always the same.
This [page](https://guides.github.com/introduction/flow/) and [that one](https://www.atlassian.com/git/tutorials/comparing-workflows/feature-branch-workflow)  explain the idea, but remember to prefix your branches with 'feature/' as it keeps them organised in a folder in SourceTree or GitKraken.

**Comment by T0T4R4** [comment]
Do you guys have a Slack/Discord channel for this project ?

**Pull request merged**
